# name: Daily Send Email Weather Information

# on:
#   schedule:
#   - cron: "0 0 * * *"
#   workflow_dispatch:

# env:
#   HOST_BACKEND: ${{ secrets.HOST_BACKEND }}
#   EMAIL_USER: ${{ secrets.EMAIL_USER }}
#   EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
#   EMAIL_SOURCE: ${{ secrets.EMAIL_SOURCE }}
# jobs:
#   report:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - run: npm ci
#       - run: npm start
